server:
  port: 8089

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/monitoring?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: fraud-detection-app
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde

product:
  base-url: http://localhost:8083